config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available wit
  # hin this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root 'schools#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  devise_for :users

  get 'home', to: 'static_page#index'
  get 'about', to: 'static_page#about'
  get 'contact', to: 'static_page#contact'

  get 'users', to: 'static_page#users'

  resources :student_lists

  get 'mark_sheets', to: 'mark_sheets#index'
  get 'mark_sheets/:id', to: 'mark_sheets#show'
  post 'mark_sheets', to: 'mark_sheets#create'
  patch 'mark_sheets/:id', to: 'mark_sheets#update'
  delete 'mark_sheets/:id', to: 'mark_sheets#destroy'

  resources :schools
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord

  validates :school_name, presence: true
  validates :school_place, presence: true
end

app/models/student_list.rb
class StudentList < ApplicationRecord
  has_many :mark_sheets, dependent: :destroy

  validates :student_name, presence: true
  validates :student_class, presence: true
  validates :student_std, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable

  validates :email, email: true

  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:school_name, :school_place)
    end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def users
    redirect_to :action => :index
  end
end

app/controllers/student_lists_controller.rb
class StudentListsController < ApplicationController
  before_action :set_student_list, only: [:show, :edit, :update, :destroy]

  # GET /student_lists
  # GET /student_lists.json
  def index
    @student_lists = StudentList.all
  end

  # GET /student_lists/1
  # GET /student_lists/1.json
  def show
  end

  # GET /student_lists/new
  def new
    @student_list = StudentList.new
  end

  # GET /student_lists/1/edit
  def edit
  end

  # POST /student_lists
  # POST /student_lists.json
  def create
    @student_list = StudentList.new(student_list_params)

    respond_to do |format|
      if @student_list.save
        format.html { redirect_to @student_list, notice: 'Student list was successfully created.' }
        format.json { render :show, status: :created, location: @student_list }
      else
        format.html { render :new }
        format.json { render json: @student_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_lists/1
  # PATCH/PUT /student_lists/1.json
  def update
    respond_to do |format|
      if @student_list.update(student_list_params)
        format.html { redirect_to @student_list, notice: 'Student list was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_list }
      else
        format.html { render :edit }
        format.json { render json: @student_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_lists/1
  # DELETE /student_lists/1.json
  def destroy
    @student_list.destroy
    respond_to do |format|
      format.html { redirect_to student_lists_url, notice: 'Student list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_list
      @student_list = StudentList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_list_params
      params.require(:student_list).permit(:student_name, :student_class, :student_std)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Page Title
  def full_title(page_title = '')
   base_title = "Unit Test"
   if page_title.empty?
     base_title
   else
     page_title + " - " + base_title
   end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join


    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/student_lists_helper.rb
module StudentListsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><%=
        Rails.application.class.parent_name
      %></a>
    </div>

    <% if !current_user.nil? %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Manage School", schools_path %></li>
    </ul>

    <% end %>

    <% if current_user.nil? %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="JavaScript:void(0);"><%= current_user.email %></a></li>
        <li>
          <a rel="nofollow" data-method="delete" href="/users/sign_out"><span class="glyphicon glyphicon-log-out"></span>Logout</a>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

  <body>
     <%= render 'layouts/header' %>

     <div class="container">
       <%= yield %>
     </div>
  </body>
</html>

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :school_name %>
    <%= form.text_field :school_name, class: "form-control"  %>
  </div>

  <div class="field">
    <%= form.label :school_place %>
    <%= form.text_field :school_place, class: "form-control"  %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>
<br>

app/views/schools/edit.html.erb
<% provide(:title, "Edit Schools") %>

<div class="row">
  <div class="col-sm-5">

<h1>Edit School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

  </div>
</div>

app/views/schools/index.html.erb
<% provide(:title, "All Schools") %>

<div class="row">
  <div class="col-sm-5">

<h1>Schools</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>School name</th>
      <th>School place</th>
      <th colspan="3" style="text-align: center;">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.school_name %></td>
        <td><%= school.school_place %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

  </div>
</div>

app/views/schools/new.html.erb
<% provide(:title, "Create School") %>

<div class="row">
<div class="col-sm-4">

<h1>Create School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

  </div>
</div>

app/views/schools/show.html.erb
<% provide(:title, "School Details") %>

<div class="row">
  <div class="col-sm-4">

<p>
  <strong>School name:</strong>
  <%= @school.school_name %>
</p>

<p>
  <strong>School place:</strong>
  <%= @school.school_place %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>
  </div>
</div>

app/views/static_page/about.html.erb
<% provide(:title, "About") %>

<h1>StaticPage#about</h1>
<p>Find me in app/views/static_page/about.html.erb</p>

app/views/static_page/contact.html.erb
<% provide(:title, "Contact") %>

<h1>StaticPage#contact</h1>
<p>Find me in app/views/static_page/contact.html.erb</p>

app/views/static_page/index.html.erb
<% provide(:title, "Home") %>

app/views/student_lists/_form.html.erb
<%= form_with(model: student_list, local: true) do |form| %>
  <% if student_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_list.errors.count, "error") %> prohibited this student_list from being saved:</h2>

      <ul>
      <% student_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_name %>
    <%= form.text_field :student_name %>
  </div>

  <div class="field">
    <%= form.label :student_class %>
    <%= form.text_field :student_class %>
  </div>

  <div class="field">
    <%= form.label :student_std %>
    <%= form.text_field :student_std %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/student_lists/edit.html.erb
<h1>Editing Student List</h1>

<%= render 'form', student_list: @student_list %>

<%= link_to 'Show', @student_list %> |
<%= link_to 'Back', student_lists_path %>

app/views/student_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Lists</h1>

<table>
  <thead>
    <tr>
      <th>Student name</th>
      <th>Student class</th>
      <th>Student std</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_lists.each do |student_list| %>
      <tr>
        <td><%= student_list.student_name %></td>
        <td><%= student_list.student_class %></td>
        <td><%= student_list.student_std %></td>
        <td><%= link_to 'Show', student_list %></td>
        <td><%= link_to 'Edit', edit_student_list_path(student_list) %></td>
        <td><%= link_to 'Destroy', student_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student List', new_student_list_path %>

app/views/student_lists/new.html.erb
<h1>New Student List</h1>

<%= render 'form', student_list: @student_list %>

<%= link_to 'Back', student_lists_path %>

app/views/student_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student name:</strong>
  <%= @student_list.student_name %>
</p>

<p>
  <strong>Student class:</strong>
  <%= @student_list.student_class %>
</p>

<p>
  <strong>Student std:</strong>
  <%= @student_list.student_std %>
</p>

<%= link_to 'Edit', edit_student_list_path(@student_list) %> |
<%= link_to 'Back', student_lists_path %>